name: lab_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.0.0
  
  # Use file_selector for all platforms
  file_selector: ^1.0.3
  file_selector_linux: ^0.9.2+1
  file_selector_macos: ^0.9.3+3
  file_selector_windows: ^0.9.3+1

  # Disable file_picker on desktop platforms by disabling it in lint warnings
  file_picker: ^6.1.1

  cupertino_icons: ^1.0.8
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1

flutter:
  uses-material-design: true
